In [1]:
import pandas as pd
from pathlib import Path
import json

### Запуска скрипт для CV и смотрим на результат

In [2]:
!python baseline.py --data_type "cv" --output_file_name "baseline_cv"

100%|█████████████████████████████████████████| 581/581 [12:52<00:00,  1.33s/it]
✅ Файл сохранен
Количество пустых кейсов 10

In [3]:
current_dir = Path.cwd()
data_dir = current_dir.parent.parent / "data"

In [4]:
df = pd.read_csv(data_dir / "baseline_cv.csv")
df.head(2)

,name,cv,llm_analysis,llm_score
0,Adam Mazilescu,Curriculum Vitae\n[name] [surname]\n+2 *** ***...,Кандидат обладает сильным профилем в биоинформ...,8
1,Adam Wieloch,[name]\n[compaany]\n+2 *** *** ***\n[email]\n[...,Кандидат имеет сильный профиль в области машин...,7

In [5]:
df.shape

(581, 4)

In [6]:
df[df.cv.isna()]

                                         name   cv llm_analysis  llm_score
364                                   Mohamma  NaN            -         -1
560                           aflyatunov_amir  NaN            -         -1
561                       aleksandrova_ulyana  NaN            -         -1
562                   anon_projects_scores.cs  NaN            -         -1
563   anonymized_test_project_scores_final.cs  NaN            -         -1
564  anonymized_test_project_scores_final.xls  NaN            -         -1
565                          offline_tests.cs  NaN            -         -1
566                         prof_eval_anon.cs  NaN            -         -1
567                        prof_eval_anon.xls  NaN            -         -1
568                student_evaluation_main.cs  NaN            -         -1

In [14]:
df = df[~df.cv.isna()]
df = df.drop_duplicates("name")
df.shape

(564, 4)

### Посмотрим корреляцию

In [8]:
dataset = pd.read_parquet(data_dir / "dataset.parquet").reset_index()
dataset.head(2)

,name,cv,letter,presentation,cv_phd_1,cv_phd_2,letter_phd_1,letter_phd_2,pres_phd_1,pres_phd_2,...,offline_test_1,offline_test_2,offline_test_3,offline_test_4,offline_test_total,online_test_score,project_participation_flag,school_participation_flag,project_ta_score,project_peer_score
0,Adam Mazilescu,Curriculum Vitae\n[name] [surname]\n+2 *** ***...,"Hello, dear members of the admissions committe...",Prediction of motifs of transcription factor b...,3.25,3.0,3.50,4.75,7.00,8.00,...,NaN,NaN,NaN,NaN,NaN,55.0,True,True,3.0,9.5
1,Adam Wieloch,[name]\n[compaany]\n+2 *** *** ***\n[email]\n[...,Motivation letter\nI’ve been working in Data S...,Introduction\n• Goal is to reproduce Dall-E\n•...,4.00,3.5,3.25,4.25,5.75,6.25,...,NaN,NaN,NaN,NaN,NaN,0.0,False,True,NaN,NaN

In [12]:
dataset.shape

(581, 27)

In [13]:
dataset = dataset.drop_duplicates("name")
dataset.shape

(574, 27)

In [18]:
df = df.merge(dataset[["name", "cv", "cv_phd_1", "cv_phd_2"]], on=["name", "cv"], how="left")

In [21]:
df["cv_phd_mean"] = df[["cv_phd_1", "cv_phd_2"]].mean(axis=1)

In [23]:
df[["llm_score", "cv_phd_mean"]].corr(method="pearson")

             llm_score  cv_phd_mean
llm_score     1.000000     0.328358
cv_phd_mean   0.328358     1.000000